# Generated by Django 5.0.6 on 2024-05-20 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='reg_date',
        ),
    ]
